### ISSUE TITLE
[BUG] semua command tidak merespon

### ISSUE THREAD

**Issue by AzRyCb** [amiruldev20/Baileys#5]
TypeError: .proto.ContextInfo.mentionedJid: array expected
    at Function.fromObject (C:\Bot\azbotzd\node_modules\@adiwajshing\baileys\WAProto\index.js:8062:27)
    at Function.fromObject (C:\Bot\azbotzd\node_modules\@adiwajshing\baileys\WAProto\index.js:25651:67)
    at Function.fromObject (C:\Bot\azbotzd\node_modules\@adiwajshing\baileys\WAProto\index.js:18716:87)
    at generateWAMessageContent (C:\Bot\azbotzd\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:355:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at generateWAMessage (C:\Bot\azbotzd\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:424:59)
    at Object.sendMessage (C:\Bot\azbotzd\node_modules\@adiwajshing\baileys\lib\Socket\messages-send.js:503:33) unhandledRejection
TypeError: .proto.ContextInfo.mentionedJid: array expected
    at Function.fromObject (C:\Bot\azbotzd\node_modules\@adiwajshing\baileys\WAProto\index.js:8062:27)
    at Function.fromObject (C:\Bot\azbotzd\node_modules\@adiwajshing\baileys\WAProto\index.js:25651:67)
    at Function.fromObject (C:\Bot\azbotzd\node_modules\@adiwajshing\baileys\WAProto\index.js:18716:87)
    at generateWAMessageContent (C:\Bot\azbotzd\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:355:36)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at generateWAMessage (C:\Bot\azbotzd\node_modules\@adiwajshing\baileys\lib\Utils\messages.js:424:59)
    at Object.sendMessage (C:\Bot\azbotzd\node_modules\@adiwajshing\baileys\lib\Socket\messages-send.js:503:33) unhandledRejection

**Comment by amiruldev20** [comment]
bisa kirimkan pesan codenya? sepertinya ada masalah pada contextInfo. tetapi botku berjalan dengan aman

**Comment by AzRyCb** [comment]
Setiap conn.reply sama m.reply eror gitu
Cuman itu aja si kalo button list dll aman aman aja

**Comment by amiruldev20** [comment]
saya aman tuh biasa make m.reply
kodemu kali

**Comment by AzRyCb** [comment]
Pake baileys yg ori aman aman aja kaya fitur speed database dll tapi pake yg kau error atau versi up to date inu

**Comment by AzRyCb** [comment]
Btw sy oake versi esm type plugins

**Comment by amiruldev20** [comment]
silahkan login gc. saya tes aman" aja https://chat.whatsapp.com/E2mrOtTJHpn6bUJPJX5tjC
